---
zabbix_export:
  version: '7.4'
  template_groups:
    - uuid: 625c9a0c501748e6b24072d52561a235
      name: Netology
  templates:
    - uuid: d0fcd142bf014960ac4cb62951f8192d
      template: Netology
      name: Netology
      groups:
        - name: Netology
      items:
        - uuid: 005c9a0c501748e6b24072d52561a235
          name: Incoming (Bytes)
          type: ZABBIX_ACTIVE
          key: net.if.in[eth0,bytes]
          value_type: UNSIGNED
          units: Bps
        - uuid: 015c9a0c501748e6b24072d52561a235
          name: Outgoing (Bytes)
          type: ZABBIX_ACTIVE
          key: net.if.out[eth0,bytes]
          value_type: UNSIGNED
          units: Bps
        - uuid: 025c9a0c501748e6b24072d52561a235
          name: Network Total Drops
          type: ZABBIX_ACTIVE
          key: net.if.total[eth0,dropped]
          value_type: UNSIGNED
          triggers:
            - uuid: 035c9a0c501748e6b24072d52561a235
              expression: 'last(/Netology/net.if.total[eth0,dropped])>100'
              name: Network packet drops are high on {HOST.NAME}
              priority: WARNING
        - uuid: 045c9a0c501748e6b24072d52561a235
          name: CPU Load
          type: ZABBIX_ACTIVE
          key: system.cpu.load[all,avg1]
          value_type: FLOAT
          triggers:
            - uuid: 055c9a0c501748e6b24072d52561a235
              expression: 'last(/Netology/system.cpu.load[all,avg1])>5'
              name: High CPU load on {HOST.NAME}
              priority: AVERAGE
        - uuid: 065c9a0c501748e6b24072d52561a235
          name: CPU Context Switches
          type: ZABBIX_ACTIVE
          key: system.cpu.switches
          value_type: UNSIGNED
          triggers:
            - uuid: 075c9a0c501748e6b24072d52561a235
              expression: 'change(/Netology/system.cpu.switches)>10000'
              name: Sudden spike in CPU context switches on {HOST.NAME}
              priority: INFO
        - uuid: 085c9a0c501748e6b24072d52561a235
          name: CPU Utilization
          type: ZABBIX_ACTIVE
          key: system.cpu.util[all,avg1]
          value_type: FLOAT
          units: "%"
          triggers:
            - uuid: 095c9a0c501748e6b24072d52561a235
              expression: 'avg(/Netology/system.cpu.util[all,avg1],5m)>90'
              name: CPU utilization is over 90% on {HOST.NAME}
              priority: WARNING
        - uuid: 105c9a0c501748e6b24072d52561a235
          name: Swap Utilization
          type: ZABBIX_ACTIVE
          key: system.swap.size[all,pused]
          value_type: FLOAT
          units: "%"
          triggers:
            - uuid: 115c9a0c501748e6b24072d52561a235
              expression: 'last(/Netology/system.swap.size[all,pused])>10'
              name: System is starting to swap on {HOST.NAME}
              priority: AVERAGE
        - uuid: 125c9a0c501748e6b24072d52561a235
          name: Disk Space Utilization
          type: ZABBIX_ACTIVE
          key: vfs.fs.size[/,pused]
          value_type: FLOAT
          units: "%"
          triggers:
            - uuid: 135c9a0c501748e6b24072d52561a235
              expression: 'last(/Netology/vfs.fs.size[/,pused])>80'
              name: Disk space critical on {HOST.NAME}
              priority: HIGH
        - uuid: 145c9a0c501748e6b24072d52561a235
          name: Memory Utilization
          type: ZABBIX_ACTIVE
          key: vm.memory.size[pused]
          value_type: FLOAT
          units: "%"
          triggers:
            - uuid: 155c9a0c501748e6b24072d52561a235
              expression: 'last(/Netology/vm.memory.size[pused])>80'
              name: RAM usage critical on {HOST.NAME}
              priority: HIGH
      dashboards:
        - uuid: d15c9a0c501748e6b24072d52561a235
          name: 'Servers'
          pages:
            - name: Overview
              widgets:
                - type: GRAPH
                  width: '36'
                  height: '5'
                  fields:
                    - type: GRAPH
                      name: graphid
                      value:
                        host: Netology
                        name: 'CPU Performance: Utilization and Load'

                - type: GRAPH
                  name: 'Memory & Swap'
                  'x': '36'
                  width: '36'
                  height: '5'
                  fields:
                    - type: GRAPH
                      name: graphid
                      value:
                        host: Netology
                        name: 'Memory Health: RAM and Swap %'

                - type: GRAPH
                  name: 'Network Traffic'
                  'y': '5'
                  width: '36'
                  height: '5'
                  fields:
                    - type: GRAPH
                      name: graphid
                      value:
                        host: Netology
                        name: 'Network Traffic: eth0 In/Out'

                - type: GRAPH
                  name: 'System Overhead'
                  'x': '36'
                  'y': '5'
                  width: '36'
                  height: '5'
                  fields:
                    - type: GRAPH
                      name: graphid
                      value:
                        host: Netology
                        name: 'System Overhead: Drops and Context Switches'

  graphs:
    - uuid: 175c9a0c501748e6b24072d52561a235
      name: 'CPU Performance: Utilization and Load'
      graph_items:
        - color: 1A7C11
          item:
            host: Netology
            key: system.cpu.util[all,avg1]
        - sortorder: '1'
          color: F63131
          yaxisside: RIGHT
          item:
            host: Netology
            key: system.cpu.load[all,avg1]
    - uuid: 185c9a0c501748e6b24072d52561a235
      name: 'Network Traffic: eth0 In/Out'
      graph_items:
        - color: 199C0D
          drawtype: GRADIENT_LINE
          item:
            host: Netology
            key: net.if.in[eth0,bytes]
        - sortorder: '1'
          color: F63131
          item:
            host: Netology
            key: net.if.out[eth0,bytes]
    - uuid: 195c9a0c501748e6b24072d52561a235
      name: 'Memory Health: RAM and Swap %'
      ymin_type_1: FIXED
      ymax_type_1: FIXED
      graph_items:
        - color: 277DB3
          item:
            host: Netology
            key: vm.memory.size[pused]
        - sortorder: '1'
          color: FF5500
          item:
            host: Netology
            key: system.swap.size[all,pused]
    - uuid: 205c9a0c501748e6b24072d52561a235
      name: 'System Overhead: Drops and Context Switches'
      graph_items:
        - color: '000000'
          item:
            host: Netology
            key: net.if.total[eth0,dropped]
        - sortorder: '1'
          color: 6C59DC
          yaxisside: RIGHT
          item:
            host: Netology
            key: system.cpu.switches
